DROP TABLE IF EXISTS EMPLOYEE_PROJECTS;
DROP TABLE IF EXISTS DEPENDENT;
DROP TABLE IF EXISTS PROJECT;
ALTER TABLE EMPLOYEE DROP CONSTRAINT Department_FK;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS EMPLOYEE;
